package com.example.giftlistb10.enums;

public enum StatusComplaint {
    CRUELTY_AND_SHOCKING_CONTENT,
    MANIFESTATION_OF_HATRED,
    ILLEGAL_ACTIVITIES_OR_REGULATED_PRODUCTS,
    SPAM,
    CALLS_TO_VIOLENCE_DANGEROUS_ACTIONS,
    SCENES_OF_A_PORNOGRAPHIC_NATURE,
    OTHER;
}