package com.example.giftlistb10.enums;

public enum Status {
    RESERVED,
    RESERVED_ANONYMOUSLY,
    REQUEST,
    BOOKED_CHARITY_ANONYMOUSLY,
    BOOKED_CHARITY,
    UNBOOKED_CHARITY,
    BOOKED_WISH_ANONYMOUSLY,
    BOOKED_WISH,
    UNBOOKED_WISH,
    UNBOOKED,
    PENDING,
    ADDED_CHARITY,
    ADDED_WISH,
    COMPLAINT_CHARITY,
    COMPLAINT_WISH;
}